"""Add age_bracket and model_name

Revision ID: b56e089de10f
Revises: 0001_stage4
Create Date: 2026-09-15 00:20:42.247314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b56e089de10f'
down_revision: Union[str, Sequence[str], None] = '0001_stage4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_results', sa.Column('model_name', sa.String(length=64), nullable=False, server_default='unknown'))
    op.drop_index('ix_risk_results_session_id', table_name='risk_results')
    op.create_index(op.f('ix_risk_results_session_id'), 'risk_results', ['session_id'], unique=True)
    op.add_column('screening_sessions', sa.Column('age_bracket', sa.String(length=16), nullable=False, server_default='Unknown'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_sessions', 'age_bracket')
    op.drop_index(op.f('ix_risk_results_session_id'), table_name='risk_results')
    op.create_index(op.f('ix_risk_results_session_id'), 'risk_results', ['session_id'], unique=False)
    op.drop_column('risk_results', 'model_name')
    # ### end Alembic commands ###
