"""Add Module B columns

Revision ID: d89833008070
Revises: b56e089de10f
Create Date: 2026-09-16 01:27:53.863851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd89833008070'
down_revision: Union[str, Sequence[str], None] = 'b56e089de10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_results', sa.Column('domain_classifications', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='{}'))
    op.add_column('risk_results', sa.Column('consistency_score', sa.Float(), nullable=True))
    op.add_column('screening_sessions', sa.Column('module', sa.String(length=8), nullable=False, server_default='A'))
    op.add_column('screening_sessions', sa.Column('intake_text_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_sessions', 'intake_text_hash')
    op.drop_column('screening_sessions', 'module')
    op.drop_column('risk_results', 'consistency_score')
    op.drop_column('risk_results', 'domain_classifications')
    # ### end Alembic commands ###
