"""
Stage 3 — Imputation

Fills unanswered item columns with the population median for the child's
ASQ-3 age bracket, computed from the Stage 1 training CSV.

Design decisions, stated explicitly:
  - Per-request recompute: medians are recomputed from the CSV on every
    call, not cached at startup. This is intentional — it means the CSV
    can change between requests (e.g. in development, when the generator
    is re-run) without stale cached values silently producing different
    imputations from what the current dataset would produce. The
    performance cost is acceptable at demo/prototype scale on an 8,000-row
    CSV; if it becomes a bottleneck at larger scale, caching can be added
    without changing this function's interface.

  - 17 ASQ-3-style brackets (not 3-month bins): the imputation peer group
    is now the same bracket system used in label_derivation.py, so a child
    at 2 months gets medians from 2-month-bracket peers, not from a 0-3
    month pool that mixes them with 3-month-olds. This is the correct
    age-relative comparison unit for this instrument.

    WHY NOT 3-month bins: the old 3-month bins were a pragmatic placeholder
    that predated the 17-bracket design. They are now replaced throughout
    the pipeline. Keeping them in imputation while the rest of the pipeline
    uses 17 brackets would create a misalignment between training-time
    percentile ranking (which now uses brackets) and inference-time
    imputation (which used bins), producing subtly wrong feature vectors.

  - Adjacent-bracket fallback: if a bracket has fewer than MIN_BRACKET_N
    rows in the training CSV (possible for narrow early-year brackets on
    smaller datasets), the median pool is widened to include the one or two
    immediately adjacent brackets. This is logged as a warning, not silently
    suppressed.

  - Imputed values are returned separately and NEVER merged into
    `session.answers`. This is enforced by the orchestrator — any code
    that tries to present an imputed value as a caregiver answer is a bug.

  - Mandatory items (`regression_flag`, `family_history_flag`) are never
    imputed — they must be explicitly answered. This function raises if
    either is included in `missing_item_ids`.
"""

from __future__ import annotations

import logging
import os

import pandas as pd

from .session import MANDATORY_IDS

logger = logging.getLogger(__name__)

DATA_PATH = os.path.abspath(
    os.path.join(
        os.path.dirname(__file__), "../../data/processed/screening_data_items.csv"
    )
)

# Minimum number of rows in a bracket to compute stable medians without
# borrowing from adjacent brackets. Consistent with label_derivation.py.
MIN_BRACKET_N = 20

# Columns in the CSV that are metadata, not item response columns
_NON_ITEM_COLS = frozenset({
    "child_id",
    "age_months",
    "corrected_age_months",
    "age_bracket",
    "age_bracket_ordinal",
    "family_history_flag",
    "multilingual_home_flag",
    "regression_flag",
    "risk_label",
})


def _load_medians(
    corrected_age_months: float, data_path: str = DATA_PATH
) -> dict[str, int]:
    """
    Computes per-item medians for the ASQ-3 age bracket containing
    `corrected_age_months`, from the Stage 1 CSV.

    Uses the `age_bracket` column if present in the CSV (generated by
    the updated generator). Falls back to computing brackets from
    `corrected_age_months` directly if the column is absent (e.g.
    when running against an older CSV before regeneration).

    Returns a dict of item_id -> median (int 0/1/2).
    """
    # Importing here keeps app startup fast — avoids loading age_brackets
    # at module import time in the web process when imputation is not called.
    from data.generator.age_brackets import (
        BRACKETS,
        adjacent_brackets,
        map_to_bracket_label,
    )

    df = pd.read_csv(data_path)
    target_bracket_label = map_to_bracket_label(corrected_age_months)

    # Use the pre-computed age_bracket column if available; otherwise derive it
    if "age_bracket" in df.columns:
        bracket_col = df["age_bracket"]
    else:
        logger.warning(
            "age_bracket column not found in CSV — deriving from corrected_age_months. "
            "Regenerate the CSV with the updated generator to avoid this."
        )
        bracket_col = df["corrected_age_months"].apply(map_to_bracket_label)

    item_cols = [c for c in df.columns if c not in _NON_ITEM_COLS]

    bracket_df = df[bracket_col == target_bracket_label]
    n_bracket = len(bracket_df)

    if n_bracket >= MIN_BRACKET_N:
        pool_df = bracket_df
    else:
        # Thin bracket: borrow from adjacent brackets
        target_bracket = next(b for b in BRACKETS if b.label == target_bracket_label)
        neighbors = adjacent_brackets(target_bracket)
        neighbor_labels = [n.label for n in neighbors]
        pool_df = df[bracket_col.isin([target_bracket_label] + neighbor_labels)]

        logger.warning(
            "Bracket '%s' has only %d rows in training CSV (threshold: %d). "
            "Borrowing from adjacent brackets %s for imputation medians. "
            "This is a fallback — consider increasing N_CHILDREN if it recurs.",
            target_bracket_label,
            n_bracket,
            MIN_BRACKET_N,
            neighbor_labels,
        )

    if pool_df.empty:
        # Should never happen with the full dataset; log and fall back to global medians
        logger.error(
            "Bracket '%s' and its neighbors have no rows — falling back to global medians. "
            "This is unexpected; check the training CSV.",
            target_bracket_label,
        )
        pool_df = df

    medians: dict[str, int] = {}
    for col in item_cols:
        medians[col] = int(pool_df[col].median())

    return medians


def impute_missing(
    missing_item_ids: list[str],
    corrected_age_months: float,
    data_path: str = DATA_PATH,
) -> dict[str, int]:
    """
    Returns a dict of item_id -> imputed_value for every item in
    `missing_item_ids`. Only item-column IDs are accepted — mandatory
    items raise immediately so imputation can never be used as a workaround
    for skipping them.

    The returned dict is SEPARATE from session.answers and must stay that
    way — the orchestrator uses it only to complete the feature vector for
    the model, not to update session state.
    """
    for mid in MANDATORY_IDS:
        if mid in missing_item_ids:
            raise ValueError(
                f"Mandatory item {mid!r} cannot be imputed — it must be "
                "explicitly answered by the caregiver."
            )

    if not missing_item_ids:
        return {}

    medians = _load_medians(corrected_age_months, data_path)

    result = {}
    for item_id in missing_item_ids:
        if item_id not in medians:
            raise KeyError(
                f"Item {item_id!r} not found in the training CSV. "
                "Check that item_bank.py and the CSV column names match."
            )
        result[item_id] = medians[item_id]

    return result
